### ISSUE TITLE
Change required: NodePort usage unclear

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1157]
### Related code PR

https://www.risingwave.dev/docs/current/risingwave-kubernetes/#connect-to-risingwave

### Which part(s) of the docs might be affected or should be updated? And how?

![SCR-20230814-nay](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/76710ce6-460a-4951-8fbb-9a0712059672)

I feel it is unclear where this `spec.globa.serviceType` should be put.

I am currently doing this:
```
apiVersion: v1
kind: Service
metadata:
  name: node-export-service
spec:
  selector:
    risingwave/component: frontend
    risingwave/name: risingwave
  ports:
    - name: risingwave-external
      protocol: TCP
      port: 4567
      targetPort: 4567
      nodePort: 30950
  type: NodePort
```
as another section in the `yaml` file to make the NodePort working

If we put 
```
spec:
   global:
      type: NodePort
```
 into the section of Risingwave in the `yaml` file:
```
Error from server (BadRequest): error when creating "risingwave-minio.yaml": RisingWave in version "v1alpha1" cannot be handled as a RisingWave: strict decoding error: unknown field "spec.global"
```

If the user is expected to put this into a standalone section, or if there is something else around it, I feel more clearer instructions are needed.
