### ISSUE TITLE
Document: feat(Sink): Enhanced integration with StarRocks

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1849]
This issue tracks the documentation update needed for the merged PR #14363.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14363
Source PR Merged At: 2024-02-07T09:14:14Z

**Comment by neverchanje** [comment]
This PR introduces a new WITH option called `starrocks.partial_update` that accepts 'true' or 'false'. Default is 'false'.

```yaml
  - name: starrocks.partial_update
    field_type: String
    required: false
```

It controls whether to enable [the partial update optimization](https://docs.starrocks.io/docs/sql-reference/sql-statements/data-manipulation/UPDATE/#partial-updates-in-column-mode-since-v31) in StarRocks, which improves the ingestion performance when only few columns are updated.
