### ISSUE TITLE
 Add a preview for every pull request to main branch

### ISSUE THREAD

**Issue by cloudcarver** [risingwavelabs/risingwave-docs-legacy#34]

**Comment by cloudcarver** [comment]
Closed. Finished this on AWS Amplify.
The script is 
```yml
version: 1
frontend:
  phases:
    build:
      commands:
        - yarn
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules
```
